services:
  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=animeshka"
  elastic:
    build:
      dockerfile: elasticsearch/Dockerfile
    volumes:
      - elastic-data:/var/elasticsearch/data/
      - elastic-logs:/var/elasticsearch/logs/
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  elastic-data:
  elastic-logs: