services:
  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=animeshka"
  elastic:
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"